logging:
    level:
        org:
            springframework:
                data:
                    r2dbc: DEBUG
spring:
    r2dbc:
        password: 7ujmNBV*
        url: r2dbc:pool:mysql://localhost:3306/test_db
        username: victorchu
