version: '2'

services:
  mysql80:
    image: mysql:8.0
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'victorchu'
      MYSQL_PASSWORD: '7ujmNBV*'
      MYSQL_ROOT_PASSWORD: '*IK<MNB('
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql80-data:/var/lib/mysql
volumes:
  mysql80-data: